sudo: required

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 5.3
    - php: hhvm
    - php: nightly
  fast_finish: true

install:
  - travis_retry composer self-update
  - composer validate
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-source --ignore-platform-reqs

before_script:
  - mkdir -p build/logs

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer test-coverage ; else composer test ; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer cs ; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer push-test-coverage ; fi

notifications:
  on_success: never
  on_failure: always
